import {useEffect,useRef,useState} from 'react';
import {api} from '../api';
import {displayNumber,receiptLabel} from './ProductionTables';
import {monthlySeries,annualSeries} from '../../../../packages/shared/production-charts.js';
const colors=['#1c6749','#326bad','#a6601c','#7c5295','#246f78','#a83e52'];
const months=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
function LineChart({title,labels,series,unit}){
  const host=useRef(),[width,setWidth]=useState(560),[point,setPoint]=useState(null);
  useEffect(()=>{const observer=new ResizeObserver(([entry])=>setWidth(Math.max(280,entry.contentRect.width)));observer.observe(host.current);return()=>observer.disconnect();},[]);
  const h=250,left=58,right=38,top=22,bottom=42,w=width,ys=series.flatMap(s=>s.values).filter(Number.isFinite),max=Math.max(1,...ys)*1.12;
  const x=i=>left+i*(w-left-right)/Math.max(1,labels.length-1),y=v=>h-bottom-v/max*(h-top-bottom);
  return <section className="production-chart" ref={host}><h3>{title}</h3><p className="chart-unit">{unit} · gaps indicate unavailable or not received data</p>
    <div className="production-chart-key">{series.map((s,i)=><span key={s.key}><i style={{background:colors[i%colors.length]}}/>{s.label}{s.previous?' (dashed)':''}</span>)}</div>
    {ys.length?<svg width="100%" height={h} viewBox={`0 0 ${w} ${h}`} role="img" aria-label={`${title}. ${unit}. Exact values in the table below.`}>
      {[0,1,2,3,4].map(i=><g key={i}><line x1={left} x2={w-right} y1={y(max*i/4)} y2={y(max*i/4)} stroke="#e2e8df"/><text x={left-9} y={y(max*i/4)+4} textAnchor="end" fontSize="11" fill="#566354">{displayNumber(max*i/4)}</text></g>)}
      {labels.map((l,i)=><text key={i} x={x(i)} y={h-14} textAnchor="middle" fontSize="11" fill="#566354">{width<440&&i%2&&i!==labels.length-1?'':l}</text>)}
      {series.map((s,si)=>{let path='',open=false;for(let i=0;i<s.values.length;i++){const v=s.values[i];if(v==null){open=false;continue;}path+=`${open?'L':'M'}${x(i)},${y(v)} `;open=true;}return <g key={s.key}><path d={path} fill="none" stroke={colors[si%colors.length]} strokeWidth="2.3" strokeDasharray={s.previous?'6 4':undefined}/>{s.values.map((v,i)=>v==null?null:<g key={i}><circle cx={x(i)} cy={y(v)} r="3.5" fill={colors[si%colors.length]}/><circle cx={x(i)} cy={y(v)} r="12" fill="transparent" tabIndex="0" role="button" aria-label={`${s.label}, ${labels[i]}, ${displayNumber(v)} ${unit}`} onFocus={()=>setPoint(`${s.label} · ${labels[i]}: ${displayNumber(v)} ${unit}`)} onClick={()=>setPoint(`${s.label} · ${labels[i]}: ${displayNumber(v)} ${unit}`)} onKeyDown={e=>{if(['Enter',' '].includes(e.key)){e.preventDefault();setPoint(`${s.label} · ${labels[i]}: ${displayNumber(v)} ${unit}`);}}}><title>{s.label} · {labels[i]}: {displayNumber(v)} {unit}</title></circle></g>)}</g>;})}
    </svg>:<p className="empty">No received values for this comparison.</p>}
    {point&&<p className="chart-inspection" role="status">{point}</p>}
    <details><summary>View chart values</summary><div className="data-table-scroll"><table><thead><tr><th>Series</th>{labels.map((l,i)=><th key={i}>{l}</th>)}</tr></thead><tbody>{series.map(s=><tr key={s.key}><th>{s.label}</th>{s.values.map((v,i)=><td key={i}>{displayNumber(v)}</td>)}</tr>)}</tbody></table></div></details>
  </section>;
}
export default function ProductionDashboard({estateId,selection,offline,onHighlights,onData}){
  const [meta,setMeta]=useState(null),[period,setPeriod]=useState(''),[metric,setMetric]=useState('mt'),[monthly,setMonthly]=useState([]),[annual,setAnnual]=useState([]),[current,setCurrent]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[highlight,setHighlight]=useState(true),[source,setSource]=useState('all');
  const code=selection?.startsWith(estateId+'::')?selection.split('::')[1]:null;
  useEffect(()=>{let active=true;onHighlights([]);if(offline)return;api.get('/production/meta',{params:{estateId}}).then(({data})=>{if(active){setMeta(data);setPeriod(data.latestReceived||data.months[0]||'');}}).catch(e=>active&&setError(e.response?.data?.error||e.message));return()=>{active=false;};},[estateId,offline]);
  useEffect(()=>{setSource('all');},[code]);
  useEffect(()=>{if(!period||offline)return;const c=new AbortController();setError('');setCurrent(null);onHighlights([]);api.get('/production/monthly',{params:{estateId,month:period,limit:5000},signal:c.signal}).then(({data})=>{setCurrent(data);onHighlights(highlight?data.items.filter(r=>r.palmDifference!=null&&r.palmDifference!==0&&r.mapBlockCode).map(r=>r.mapBlockCode):[]);}).catch(e=>{if(e.code!=='ERR_CANCELED')setError(e.response?.data?.error||e.message);});return()=>c.abort();},[estateId,period,highlight,offline]);
  useEffect(()=>{setMonthly([]);setAnnual([]);if(!code||offline){setBusy(false);return;}const c=new AbortController();setBusy(true);Promise.all([api.get('/production/monthly',{params:{estateId,mapBlockCode:code,limit:5000},signal:c.signal}),api.get('/production/yearly',{params:{estateId,mapBlockCode:code},signal:c.signal})]).then(([m,a])=>{setMonthly(m.data.items);setAnnual(a.data.items);setBusy(false);}).catch(e=>{if(e.code!=='ERR_CANCELED'){setError(e.response?.data?.error||e.message);setBusy(false);}});return()=>c.abort();},[estateId,code,offline]);
  const linked=(meta?.names||[]).filter(n=>n.mapBlockCode===code),rows=(current?.items||[]).filter(r=>r.mapBlockCode===code&&(source==='all'||r.sourceBlockId===source));
  const chartMonthly=monthly.filter(r=>source==='all'||r.sourceBlockId===source),chartAnnual=annual.filter(r=>source==='all'||r.sourceBlockId===source),units={mt:'MT',bunches:'bunches',abw:'kg / bunch',yieldPerHa:'MT / ha',bunchesPerHa:'bunches / ha',bunchesPerPalm:'bunches / palm'};
  const annualChart=annualSeries(chartAnnual,metric);
  return <section className="production-dashboard" aria-label="Production dashboard"><div className="production-heading"><div><div className="eyebrow">BLOCK PRODUCTION</div><h2>{code?`Production · ${code}`:'Production dashboard'}</h2><p>{code?'Original block names and their production stay separate.':'Click a block on the map to explore its monthly and yearly production.'}</p></div><button className="button" onClick={onData}>Open production tables</button></div>
    {offline?<p>Production tables require a connection. Offline field activities remain available.</p>:<>
    <div className="production-controls"><label>Reporting month<input type="month" value={period} onChange={e=>setPeriod(e.target.value)}/></label><label>Chart metric<select value={metric} onChange={e=>setMetric(e.target.value)}>{[['mt','FFB tonnage'],['bunches','Bunches'],['abw','Average bunch weight'],['yieldPerHa','Yield per hectare'],['bunchesPerHa','Bunches per hectare'],['bunchesPerPalm','Bunches per palm']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>{code&&<label>Original name / group<select value={source} onChange={e=>setSource(e.target.value)}><option value="all">All separate source series</option>{linked.map(n=><option key={n.id} value={n.id}>{n.sourceBlockCode} · {n.division}</option>)}</select></label>}<label className="check-label"><input type="checkbox" checked={highlight} onChange={e=>setHighlight(e.target.checked)}/>Highlight palm differences on map</label></div>
    {error&&<p className="production-warning" role="alert">{error}</p>}{busy&&<p role="status">Loading block history…</p>}
    {current&&<div className="production-coverage"><span><b>{current.counts.mapped}</b> mapped source records</span><span><b>{current.counts.unmapped}</b> unmapped records</span><span><b>{current.counts.palmDifferences}</b> palm-count differences</span><span><b>{current.counts.notReceived}</b> production not received</span></div>}
    {code&&period&&<><div className="production-name-history">{linked.map(n=><span key={n.id}><b>{n.sourceBlockCode}</b> · {n.division} → {n.mapBlockCode}<small>Observed {n.firstMonth} to {n.lastMonth}</small></span>)}</div>
    <div className="production-block-cards">{rows.map(r=><article key={r.id}><h3>{r.sourceBlockCode} <small>· {r.division}</small></h3><span className={'receipt '+(r.receiptStatus!=='received'?'pending':'')}>{receiptLabel(r.receiptStatus)}</span><dl><div><dt>FFB</dt><dd>{displayNumber(r.mt)} <small>MT</small></dd></div><div><dt>Bunches</dt><dd>{displayNumber(r.bunches)}</dd></div><div><dt>Average bunch weight</dt><dd>{displayNumber(r.abw)} <small>kg</small></dd></div><div><dt>Harvesting days</dt><dd>{displayNumber(r.harvestingDays)}</dd></div></dl><small>GPS {displayNumber(r.gpsHa)} ha · effective {displayNumber(r.effectiveHa)} ha · yield denominator {displayNumber(r.yieldAreaHa)} ha</small></article>)}</div>
    {!busy&&!rows.length&&<p>No monthly record for this map block in {period}. Historical records, if available, remain below.</p>}
    <div className="production-charts"><LineChart title={`Monthly comparison · ${period.slice(0,4)} and ${Number(period.slice(0,4))-1}`} labels={months} series={monthlySeries(chartMonthly,period.slice(0,4),metric)} unit={units[metric]}/><LineChart title="Yearly source comparison" labels={annualChart.labels} series={annualChart.series} unit={units[metric]}/></div>
    <p className="table-note">Imported 2026 annual figures cover Jan–Jul YTD. Imported August–December zeros mean not received; charts omit any records still marked not received. Yield uses each record’s supplied area basis; review area warnings before comparing. Annual source totals are independent of subsequent monthly edits.</p>
    </>}
    </>}
  </section>;
}
