import {useEffect,useState} from 'react';
import {api} from '../api';
export const displayNumber=v=>v==null?'—':typeof v==='number'?v.toLocaleString(undefined,{maximumFractionDigits:2}):String(v);
export const receiptLabel=s=>({received:'Received',not_received:'Production not yet received',unavailable:'Unavailable'}[s]||s);
const numericFields=[['mt','FFB (MT)'],['bunches','Bunches'],['workbookPalms','Workbook palms'],['gpsHa','GPS hectares'],['effectiveHa','Source effective hectares'],['yieldAreaHa','Yield denominator (ha)'],['sourceAbw','Source ABW (kg)'],['sourceYield','Source yield (MT/ha)'],['sourceBunchesHa','Source bunches/ha'],['sourceBunchesPalm','Source bunches/palm'],['harvestingDays','Harvesting days']];
const allowed=['sourceBlockId','month','receiptStatus',...numericFields.map(x=>x[0]),'plantingYear','parameterNote','note','sourceFile','sourceSheet','sourceRow','sourceSystem','sourceKey','sourceHash','sourceCells','issues'];
export const writableRecord=r=>Object.fromEntries(allowed.filter(k=>r[k]!==undefined).map(k=>[k,r[k]]));
const errorText=e=>e.response?.data?.error||e.message;
export default function ProductionTables({estateId,role,view,onMap}) {
  const [meta,setMeta]=useState(null),[period,setPeriod]=useState(''),[allMonths,setAllMonths]=useState(false),[q,setQ]=useState(''),[match,setMatch]=useState('all'),[page,setPage]=useState(0),[result,setResult]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[refresh,setRefresh]=useState(0),[edit,setEdit]=useState(null),[saving,setSaving]=useState(false),[history,setHistory]=useState(null),[upload,setUpload]=useState(null),[message,setMessage]=useState('');
  const canWrite=['admin','manager'].includes(role),namesView=view==='names',annual=view==='yearly';
  useEffect(()=>{let active=true;setMeta(null);api.get('/production/meta',{params:{estateId}}).then(({data})=>{if(active){setMeta(data);setPeriod(p=>p||data.latestReceived||data.months[0]||new Date().toISOString().slice(0,7));}}).catch(e=>active&&setError(errorText(e)));return()=>{active=false;};},[estateId,refresh]);
  useEffect(()=>{if(!period||namesView){setBusy(false);return;}const controller=new AbortController();setBusy(true);setResult(null);setError('');const timer=setTimeout(()=>{
    api.get(annual?'/production/yearly':'/production/monthly',{params:{estateId,...(allMonths?{year:period.slice(0,4)}:{month:period}),q,match,page,limit:25},signal:controller.signal}).then(({data})=>{if(annual){let items=data.items.filter(r=>String(r.year)===period.slice(0,4)&&(!q||[r.sourceBlockCode,r.mapBlockCode,r.division].join(' ').toLowerCase().includes(q.toLowerCase()))&&(match!=='mapped'||r.mapBlockCode)&&(match!=='unmapped'||!r.mapBlockCode)&&(match!=='differences'||(r.palmDifference!=null&&r.palmDifference!==0)));setResult({items:items.slice(page*25,(page+1)*25),count:items.length});}else setResult(data);setBusy(false);}).catch(e=>{if(e.code!=='ERR_CANCELED'){setError(errorText(e));setBusy(false);}});
  },180);return()=>{clearTimeout(timer);controller.abort();};},[estateId,period,allMonths,q,match,page,view,refresh]);
  useEffect(()=>{setPage(0);setEdit(null);setHistory(null);},[view]);
  const reload=()=>{setRefresh(x=>x+1);setEdit(null);};
  const filteredNames=(meta?.names||[]).filter(n=>(!q||[n.sourceBlockCode,n.mapBlockCode,n.division].join(' ').toLowerCase().includes(q.toLowerCase()))&&(match!=='mapped'||n.mapBlockCode)&&(match!=='unmapped'||!n.mapBlockCode));
  const rows=namesView?filteredNames.slice(page*25,(page+1)*25):result?.items||[],count=namesView?filteredNames.length:result?.count||0;
  const save=async e=>{e.preventDefault();setSaving(true);setError('');try{
    let record=namesView?Object.fromEntries(['sourceBlockCode','division','mapBlockCode','linkMethod','firstMonth','lastMonth','note'].map(k=>[k,edit[k]])):writableRecord(edit);
    if(!namesView){record.sourceSystem=edit.id?'manual correction':'manual';if(annual){record.year=Number(edit.month.slice(0,4));record.periodLabel=edit.periodLabel||'Full year';}}
    const path='/production/'+(namesView?'names':annual?'yearly':'monthly');
    await api[edit.id?'patch':'post'](path+(edit.id?'/'+edit.id:''),{estateId,revision:edit.revision||0,record});setMessage('Saved. The dashboard will use the updated record.');reload();
  }catch(e){setError(errorText(e));}finally{setSaving(false);}};
  const chooseFile=async e=>{const file=e.target.files?.[0];if(!file)return;setError('');try{const parsed=JSON.parse(await file.text()),records=(Array.isArray(parsed)?parsed:parsed.records).map(writableRecord);const {data}=await api.post('/production/import',{estateId,records,preview:true});setUpload({records,...data});}catch(e){setError(errorText(e));}e.target.value='';};
  const columns=namesView?[['sourceBlockCode','Original / source name'],['division','Planting group'],['mapBlockCode','Current map name'],['linkMethod','Link'],['firstMonth','First observed'],['lastMonth','Last observed'],['note','Notes']]:[
    [annual?'periodLabel':'month',annual?'Period':'Month'],['sourceBlockCode','Original / source name'],['division','Planting group'],['mapBlockCode','Current map name'],
    ...(view==='parameters'?[['plantingYear','Planting year'],['workbookPalms','Workbook palms'],['gisPalms','GIS palms'],['palmDifference','Difference'],['palmStatus','Palm comparison'],['gisSurveyDate','GIS survey date'],['gpsHa','Workbook GPS ha'],['gisAreaHa','GIS ha'],['effectiveHa','Source effective ha'],['yieldAreaHa','Yield denominator ha']]:[['receiptStatus','Receipt'],['mt','FFB (MT)'],['bunches','Bunches'],['abw','ABW (kg)'],['yieldPerHa','MT/ha'],['bunchesPerHa','Bunches/ha'],['bunchesPerPalm','Bunches/palm'],['harvestingDays','Harvesting days']]),['issues','Data notes'],['sourceSheet','Source sheet'],['sourceRow','Source row']];
  return <section className="production-tables">
    <p className="table-note">{namesView?'Original names are retained. Observed periods describe source coverage, not a confirmed renaming date.':annual?'Yearly source totals are retained separately. Imported 2026 figures are Jan–Jul YTD; monthly records are not combined.':'Each row is one source block and one month. Blocks sharing a polygon remain separate.'}</p>
    <div className="table-toolbar production-toolbar">
      {!namesView&&<><label>{annual?'Reporting year':'Reporting month'}<input type={annual?'number':'month'} min={annual?'1900':undefined} max={annual?'2200':undefined} value={annual?period.slice(0,4):period} onChange={e=>{setPeriod(annual?e.target.value+'-07':e.target.value);setPage(0);}}/></label>{!annual&&<label className="check-label"><input type="checkbox" checked={allMonths} onChange={e=>{setAllMonths(e.target.checked);setPage(0);}}/>Show all months of this year</label>}</>}
      <label>Search names or group<input type="search" value={q} onChange={e=>{setQ(e.target.value);setPage(0);}}/></label>
      <label>Map / review<select value={match} onChange={e=>{setMatch(e.target.value);setPage(0);}}><option value="all">All records</option><option value="mapped">Mapped only</option><option value="unmapped">Unmapped</option>{!namesView&&<option value="differences">Palm count differences</option>}</select></label>
      <span>{count.toLocaleString()} records</span>
    </div>
    {canWrite&&<div className="production-actions"><button className="button primary" onClick={()=>setEdit(namesView?{sourceBlockCode:'',division:'',mapBlockCode:null,linkMethod:'unmapped',firstMonth:period,lastMonth:period,note:''}:{sourceBlockId:meta?.names[0]?.id||'',month:period,receiptStatus:'received',mt:null,bunches:null,issues:[],periodLabel:'Full year'})}>Add {namesView?'source name':annual?'yearly record':'monthly record'}</button>{!namesView&&!annual&&<><label className="button">Import monthly JSON<input hidden type="file" accept=".json,application/json" onChange={chooseFile}/></label><button className="button" onClick={()=>{const records=[{sourceBlockId:meta?.names[0]?.id||'choose-source-block-id',month:period,receiptStatus:'received',mt:null,bunches:null,sourceSystem:'integration'}];const url=URL.createObjectURL(new Blob([JSON.stringify({records},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='monthly-production-template.json';a.click();URL.revokeObjectURL(url);}}>Import template</button></>}</div>}
    {message&&<p role="status">{message}</p>}{error&&<p className="production-warning" role="alert">{error}</p>}{busy&&<p role="status">Loading records…</p>}
    {upload&&<div className="production-warning"><p>Import preview: {upload.newRecords} new records; {upload.existingRecords} existing records will be preserved.</p><button className="button primary" disabled={saving} onClick={async()=>{setSaving(true);try{const {data}=await api.post('/production/import',{estateId,records:upload.records,preview:false});setMessage(`Imported ${data.inserted} records; preserved ${data.existing} existing records.`);setUpload(null);reload();}catch(e){setError(errorText(e));}finally{setSaving(false);}}}>Import {upload.newRecords} new records</button><button className="button" onClick={()=>setUpload(null)}>Cancel</button></div>}
    {edit&&<form className="production-editor" onSubmit={save}><h3>{edit.id?'Edit':'Add'} {namesView?'block name':annual?'yearly record':'monthly record'}</h3><div className="production-form-grid">
      {namesView?<><label>Original / source name<input required disabled={!!edit.id} value={edit.sourceBlockCode} onChange={e=>setEdit({...edit,sourceBlockCode:e.target.value})}/></label><label>Planting group<input disabled={!!edit.id} value={edit.division} onChange={e=>setEdit({...edit,division:e.target.value})}/></label><label>Current map name<select value={edit.mapBlockCode||''} onChange={e=>setEdit({...edit,mapBlockCode:e.target.value||null,linkMethod:e.target.value?'confirmed_alias':'unmapped'})}><option value="">Unmapped</option>{meta?.mapBlocks.map(c=><option key={c}>{c}</option>)}</select></label><label>Link method<select value={edit.linkMethod} onChange={e=>setEdit({...edit,linkMethod:e.target.value})}>{['code','confirmed_alias','shared_polygon','unmapped'].map(x=><option key={x}>{x}</option>)}</select></label>{['firstMonth','lastMonth'].map(k=><label key={k}>{k==='firstMonth'?'First observed':'Last observed'}<input required type="month" value={edit[k]} onChange={e=>setEdit({...edit,[k]:e.target.value})}/></label>)}</>:<><label>Source block<select required disabled={!!edit.id} value={edit.sourceBlockId} onChange={e=>setEdit({...edit,sourceBlockId:e.target.value})}>{meta?.names.map(n=><option key={n.id} value={n.id}>{n.sourceBlockCode} · {n.division} → {n.mapBlockCode||'Unmapped'}</option>)}</select></label><label>{annual?'Reporting through':'Month'}<input required disabled={!!edit.id&&!annual} type="month" value={edit.month} onChange={e=>setEdit({...edit,month:e.target.value})}/></label><label>Receipt<select value={edit.receiptStatus} onChange={e=>setEdit({...edit,receiptStatus:e.target.value})}>{['received','not_received','unavailable'].map(s=><option key={s} value={s}>{receiptLabel(s)}</option>)}</select></label>{annual&&<label>Period label<input required value={edit.periodLabel||''} onChange={e=>setEdit({...edit,periodLabel:e.target.value})}/></label>}{numericFields.map(([k,label])=><label key={k}>{label}<input type="number" min="0" step="any" value={edit[k]??''} onChange={e=>setEdit({...edit,[k]:e.target.value===''?null:Number(e.target.value)})}/></label>)}<label>Planting year<input value={edit.plantingYear||''} onChange={e=>setEdit({...edit,plantingYear:e.target.value})}/></label><label>Parameter / area basis<input value={edit.parameterNote||''} onChange={e=>setEdit({...edit,parameterNote:e.target.value})}/></label></>}
      <label className="wide">Notes<textarea value={edit.note||''} onChange={e=>setEdit({...edit,note:e.target.value})}/></label></div><p>Blank numeric fields remain unavailable. Source provenance and previous saved values are retained.</p><button className="button primary" disabled={saving}>Save record</button> <button className="button" type="button" disabled={saving} onClick={()=>setEdit(null)}>Cancel</button></form>}
    <div className="data-table-scroll" tabIndex="0"><table><thead><tr>{columns.map(([k,t])=><th key={k}>{t}</th>)}<th>Actions</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className={r.palmDifference!=null&&r.palmDifference!==0?'production-flag':''}>{columns.map(([k])=><td key={k}>{k==='receiptStatus'?receiptLabel(r[k]):k==='issues'?[...(r.issues||[]),r.note].filter(Boolean).join(' ')||'—':displayNumber(r[k])}</td>)}<td><div className="row-actions">{canWrite&&<button className="text-button" onClick={()=>{setError('');setEdit({...r});}}>Edit</button>}{r.mapBlockCode&&<button className="text-button" onClick={()=>onMap?.({estateId,blockCode:r.mapBlockCode})}>Map</button>}{!namesView&&!annual&&<button className="text-button" onClick={async()=>{try{const {data}=await api.get('/production/monthly/'+r.id+'/history',{params:{estateId}});setHistory({row:r,items:data});}catch(e){setError(errorText(e));}}}>History</button>}</div></td></tr>)}</tbody></table></div>
    {!busy&&!rows.length&&<p className="empty">No records for this selection.</p>}
    {history&&<div className="production-editor"><h3>Saved changes · {history.row.sourceBlockCode} · {history.row.month}</h3><button className="button" onClick={()=>setHistory(null)}>Close history</button>{history.items.length?history.items.map((h,i)=><p key={i}>{new Date(h.at).toLocaleString()} · {h.by} · previous FFB {displayNumber(h.previous.mt)} MT, bunches {displayNumber(h.previous.bunches)}, palms {displayNumber(h.previous.workbookPalms)}</p>):<p>No manual revisions. Original imported record.</p>}</div>}
    <div className="table-pagination"><button className="button" disabled={!page||busy} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {page+1} of {Math.max(1,Math.ceil(count/25))}</span><button className="button" disabled={busy||(page+1)*25>=count} onClick={()=>setPage(p=>p+1)}>Next</button></div>
  </section>;
}
