import {useEffect,useState} from 'react';
import {api} from '../api';
export const money=v=>v==null?'—':(v/100).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});
const failure=e=>e.response?.data?.error||e.message;
const fields=['basis','period','division','task','activity','sourceBlockCode','mapBlockCode','amountMinor','currency','sourceSystem','sourceKey','sourceDivision','sourceSerial','sourceFile','sourceSheet','sourceRow','sourceCell','sourceHash','note'];
const writable=r=>Object.fromEntries(fields.filter(k=>r[k]!==undefined).map(k=>[k,r[k]]));
const download=value=>{const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='wages-import-template.json';a.click();URL.revokeObjectURL(url);};
export default function WagesTables({estateId,role,onMap}){
  const [year,setYear]=useState('2025'),[basis,setBasis]=useState('allocated'),[division,setDivision]=useState(''),[q,setQ]=useState(''),[match,setMatch]=useState('all'),[page,setPage]=useState(0),[meta,setMeta]=useState(null),[result,setResult]=useState(null),[edit,setEdit]=useState(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[refresh,setRefresh]=useState(0),[busy,setBusy]=useState(false),[upload,setUpload]=useState(null),[history,setHistory]=useState(null);
  const areas=basis==='areas',allocated=basis==='allocated',canWrite=['admin','manager'].includes(role);
  useEffect(()=>{const c=new AbortController();api.get('/wages/meta',{params:{estateId,year},signal:c.signal}).then(({data})=>setMeta(data)).catch(e=>{if(e.code!=='ERR_CANCELED')setError(failure(e));});return()=>c.abort();},[estateId,year,refresh]);
  useEffect(()=>{const c=new AbortController();setResult(null);setError('');api.get(areas?'/wages/areas':allocated?'/wages/allocation':'/wages',{params:{estateId,year,basis:allocated?'monthly':basis,division:division||undefined,q,match,page},signal:c.signal}).then(({data})=>setResult(data)).catch(e=>{if(e.code!=='ERR_CANCELED')setError(failure(e));});return()=>c.abort();},[estateId,year,basis,division,q,match,page,refresh]);
  const filtered=(result?.items||[]).filter(r=>!areas||((!division||r.division===division)&&(!q||[r.sourceBlockCode,r.mapBlockCode,r.division].join(' ').toLowerCase().includes(q.toLowerCase()))&&(match==='all'||match==='mapped'&&r.mapBlockCode||match==='unmapped'&&!r.mapBlockCode||match==='group'&&(r.mapHa==null||r.division==='DIVISION NOT SET'))));
  const rows=areas?filtered.slice(page*25,(page+1)*25):filtered,count=areas?filtered.length:result?.count||0;
  const change=(setter,value)=>{setter(value);setPage(0);setEdit(null);setUpload(null);setHistory(null);};
  const reload=()=>{setRefresh(n=>n+1);setEdit(null);setUpload(null);};
  const save=async event=>{event.preventDefault();setBusy(true);setError('');try{
    const record=areas?edit.id?{division:edit.division,note:edit.note||''}:{year:Number(year),mapBlockCode:edit.mapBlockCode,division:edit.division,note:edit.note||''}:writable(edit);
    await api[edit.id?'patch':'post']('/wages'+(areas?'/areas':'')+(edit.id?'/'+edit.id:''),{estateId,revision:edit.revision||0,record});setMessage('Saved. Wage allocations recalculate from the saved costs and areas.');reload();
  }catch(e){setError(failure(e));}finally{setBusy(false);}};
  const template={basis:areas?'monthly':basis,period:basis==='annual_summary'?year:year+'-01',division:division||'RO',task:'UPKEEP',activity:'Replace with activity',sourceBlockCode:null,mapBlockCode:null,amountMinor:0,currency:'NGN',sourceSystem:'your-source',sourceKey:'unique-record-id',note:''};
  return <section className="production-tables" aria-label="Wages data tables">
    <p className="table-note">Monthly wages and annual summaries are independent sources. Allocation areas use map GIS hectares once per polygon. Only mapped blocks participate in the area denominator. Only division costs that can be allocated to mapped blocks are stored. Costs outside those blocks are excluded.</p>
    <div className="production-toolbar table-toolbar">
      <label>Wages table<select value={basis} onChange={e=>change(setBasis,e.target.value)}><option value="allocated">Allocated block costs</option><option value="monthly">Monthly allocation source records</option><option value="annual_summary">Annual division summaries</option><option value="areas">Allocation areas</option></select></label>
      <label>Wage year<input type="number" min="1900" max="2200" value={year} onChange={e=>change(setYear,e.target.value)}/></label>
      <label>Division<select value={division} onChange={e=>change(setDivision,e.target.value)}><option value="">All divisions</option>{meta?.divisions.map(d=><option key={d}>{d}</option>)}</select></label>
      <label>Search wages<input type="search" value={q} onChange={e=>change(setQ,e.target.value)}/></label>
      {!allocated&&<label>Coverage<select value={match} onChange={e=>change(setMatch,e.target.value)}><option value="all">All records</option><option value="mapped">Mapped blocks</option><option value="group">{areas?'Missing area / division':'Allocation source costs'}</option></select></label>}
    </div>
    <p><b>{count.toLocaleString()}</b> records{!areas&&result&&<> · Filtered total: <b>NGN {money(result.amountMinor)}</b></>}</p>
    {canWrite&&!allocated&&<div className="production-actions"><button className="button primary" onClick={()=>setEdit(areas?{mapBlockCode:meta?.mapBlocks[0]||'',division:division||'',note:''}:{...template,activity:'',task:'',sourceSystem:'manual',sourceKey:crypto.randomUUID()})}>Add {areas?'allocation area':'wage record'}</button>{!areas&&<><label className="button">Import wages JSON<input hidden type="file" accept=".json,application/json" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;setError('');try{const value=JSON.parse(await file.text()),records=Array.isArray(value)?value:value.records;const {data}=await api.post('/wages/import',{estateId,records,preview:true});setUpload({records,...data});}catch(err){setError(failure(err));}e.target.value='';}}/></label><button className="button" onClick={()=>download({records:[template]})}>Import template</button></>}</div>}
    {message&&<p role="status">{message}</p>}{error&&<p role="alert" className="production-warning">{error}</p>}{!result&&!error&&<p role="status">Loading wages…</p>}
    {upload&&<div className="production-warning"><p>{upload.newRecords} new records; {upload.existingRecords} existing records will be preserved. Amounts use integer kobo (100 kobo = NGN 1).</p><button className="button primary" disabled={busy} onClick={async()=>{setBusy(true);try{const {data}=await api.post('/wages/import',{estateId,records:upload.records,preview:false});setMessage(`Imported ${data.inserted} records; preserved ${data.existing} existing records.`);reload();}catch(e){setError(failure(e));}finally{setBusy(false);}}}>Import new records</button><button className="button" onClick={()=>setUpload(null)}>Cancel</button></div>}
    {edit&&<form className="production-editor" onSubmit={save}><h3>{edit.id?'Edit':'Add'} {areas?'allocation area':'wage record'}</h3><div className="production-form-grid">
      {areas?<><label>Map block{edit.id?<input disabled value={edit.mapBlockCode}/>:<select required value={edit.mapBlockCode} onChange={e=>setEdit({...edit,mapBlockCode:e.target.value})}>{meta?.mapBlocks.map(n=><option key={n}>{n}</option>)}</select>}</label><label>Division<input required value={edit.division} onChange={e=>setEdit({...edit,division:e.target.value})}/></label><label>Map hectares<input disabled value={edit.mapHa??'Loaded from map when saved'}/></label></>:<>
        <label>{basis==='monthly'?'Wage month':'Wage year'}<input required disabled={!!edit.id} type={basis==='monthly'?'month':'number'} value={edit.period} onChange={e=>setEdit({...edit,period:e.target.value})}/></label>
        {[['division','Division'],['task','Task name'],['activity','Activity name']].map(([key,label])=><label key={key}>{label}<input required disabled={!!edit.id} value={edit[key]} maxLength="200" onChange={e=>setEdit({...edit,[key]:e.target.value})}/></label>)}
        <label>Task No / source S/N<input disabled={!!edit.id} value={edit.sourceSerial||''} onChange={e=>setEdit({...edit,sourceSerial:e.target.value})}/></label><label>Original block number (for direct block costs)<input disabled={!!edit.id||basis==='annual_summary'} value={edit.sourceBlockCode||''} onChange={e=>setEdit({...edit,sourceBlockCode:e.target.value||null,mapBlockCode:e.target.value?edit.mapBlockCode:null})}/></label>
        <label>Map block<select disabled={!edit.sourceBlockCode} value={edit.mapBlockCode||''} onChange={e=>setEdit({...edit,mapBlockCode:e.target.value||null})}><option value="">Division allocation source</option>{meta?.mapBlocks.map(c=><option key={c}>{c}</option>)}</select></label>
        <label>Wage amount (NGN)<input required type="number" step="0.01" value={edit.amountMinor==null?'':edit.amountMinor/100} onChange={e=>setEdit({...edit,amountMinor:e.target.value===''?null:Math.round(Number(e.target.value)*100)})}/></label>
      </>}
      <label className="wide">Notes<textarea value={edit.note||''} onChange={e=>setEdit({...edit,note:e.target.value})}/></label></div>
      <p>{areas?'Saving loads the current GIS hectares from the map block table and preserves the previous allocation snapshot. Edit the division here if it is missing or incorrect.':'Original identities and prior values are preserved. Negative amounts can record corrections or reversals.'}</p>
      <button className="button primary" disabled={busy}>Save record</button> <button className="button" type="button" onClick={()=>setEdit(null)}>Cancel</button></form>}
    <div className="data-table-scroll" tabIndex="0"><table><thead><tr>{(allocated?['Period','Block','Division','Task No / S/N','Task','Activity','Rate (NGN/ha)','Block cost (NGN)']:areas?['Block','Division','Map block','Map ha','GIS survey date','Source']:['Period','Division','Task No / source S/N','Task','Activity','Original block','Map block','Wages (NGN)','Source']).map(h=><th key={h}>{h}</th>)}<th>Actions</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className={areas&&(r.mapHa==null||r.division==='DIVISION NOT SET')?'production-flag':''}>
      {(allocated?[r.period,r.mapBlockCode,r.division,r.taskNumbers.join(', '),r.task,r.activity,(r.rateMinorPerHa/100).toLocaleString(undefined,{minimumFractionDigits:4,maximumFractionDigits:4}),money(r.amountMinor)]:areas?[r.sourceBlockCode,r.division,r.mapBlockCode,r.mapHa==null?'Missing':r.mapHa.toLocaleString(undefined,{maximumFractionDigits:4}),r.sourcePeriod,`${r.sourceSheet||'Manual'} ${r.sourceCell||''}`]:[r.period,r.division,r.sourceSerial,r.task,r.activity,r.sourceBlockCode,r.mapBlockCode,money(r.amountMinor),`${r.sourceSheet||r.sourceSystem} ${r.sourceCell||''}`]).map((v,i)=><td key={i}>{v??'—'}</td>)}
      <td><div className="row-actions">{canWrite&&!allocated&&<button className="text-button" onClick={()=>{setError('');setEdit({...r});}}>Edit</button>}{r.mapBlockCode&&<button className="text-button" onClick={()=>onMap?.({estateId,blockCode:r.mapBlockCode})}>Map</button>}{!areas&&!allocated&&<button className="text-button" onClick={async()=>{try{const {data}=await api.get('/wages/'+r.id+'/history',{params:{estateId}});setHistory(data);}catch(e){setError(failure(e));}}}>History</button>}</div></td></tr>)}</tbody></table></div>
    {history&&<div className="production-editor"><button className="text-button" onClick={()=>setHistory(null)}>Close history</button>{history.length?history.map((h,i)=><p key={i}>{new Date(h.at).toLocaleString()} · {h.by} · previous amount NGN {money(h.previous.amountMinor)}</p>):<p>No revisions. Original source record.</p>}</div>}
    <div className="table-pagination"><button className="button" disabled={!page} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {page+1} of {Math.max(1,Math.ceil(count/25))}</span><button className="button" disabled={(page+1)*25>=count} onClick={()=>setPage(p=>p+1)}>Next</button></div>
  </section>;
}
