import {useEffect,useState} from 'react';
import {api} from '../api';
import {money} from './WagesTables';
function Breakdown({title,rows}){
  const max=Math.max(1,...rows.map(r=>Math.abs(r.amountMinor)));
  return <section className="production-chart wages-breakdown"><h3>{title}</h3><p className="chart-unit">NGN · exact values shown alongside each bar</p>{rows.length?rows.map(r=><div className="wages-bar-row" key={r.name}><span>{r.name}</span><b>{money(r.amountMinor)}</b><div className="wages-bar-track"><i style={{width:`${Math.abs(r.amountMinor)/max*100}%`}}/></div></div>):<p>No available values.</p>}</section>;
}
export default function WagesDashboard({estateId,selection,offline,onData}){
  const mode='allocated';
  const [year,setYear]=useState('2025'),[basis,setBasis]=useState('monthly'),[task,setTask]=useState(''),[activity,setActivity]=useState(''),[meta,setMeta]=useState(null),[data,setData]=useState(null),[error,setError]=useState(''),[page,setPage]=useState(0);
  const code=selection?.startsWith(estateId+'::')?selection.split('::')[1]:null;
  useEffect(()=>{setPage(0);},[code,year,basis,mode,task,activity]);
  useEffect(()=>{if(offline)return;const c=new AbortController();api.get('/wages/meta',{params:{estateId,year,task:task||undefined},signal:c.signal}).then(({data})=>setMeta(data)).catch(e=>{if(e.code!=='ERR_CANCELED')setError(e.response?.data?.error||e.message);});return()=>c.abort();},[estateId,year,task,offline]);
  useEffect(()=>{setData(null);setError('');if(offline)return;const c=new AbortController();api.get(mode==='allocated'?'/wages/allocation':'/wages',{params:{estateId,year,basis,task:task||undefined,activity:activity||undefined,mapBlockCode:code||undefined,page,...(mode==='recorded'?{match:'mapped'}:{})},signal:c.signal}).then(({data})=>setData(data)).catch(e=>{if(e.code!=='ERR_CANCELED')setError(e.response?.data?.error||e.message);});return()=>c.abort();},[estateId,year,basis,mode,task,activity,code,page,offline]);
  const selectedGroups=new Set((data?.selectedAreas||[]).map(a=>a.division));
  const coverage=(data?.coverage||[]).filter(c=>!code||selectedGroups.has(c.division));
  return <section className="production-dashboard" aria-label="Wages dashboard"><div className="production-heading"><div><div className="eyebrow">WAGES · NGN</div><h2>{code?`Wages · ${code}`:'Wages dashboard'}</h2><p>{mode==='allocated'?'Area-allocated estimates using map hectares. Original wage records stay separate.':'Wages explicitly recorded against a block number.'}</p></div><button className="button" onClick={onData}>Open wages tables</button></div>
    {offline?<p>Wages require a connection.</p>:<>
    <div className="production-controls"><label>Wage year<input type="number" min="1900" max="2200" value={year} onChange={e=>setYear(e.target.value)}/></label><label>Cost source<select value={basis} onChange={e=>setBasis(e.target.value)}><option value="monthly">Monthly wage records</option><option value="annual_summary">Annual division summary</option></select></label><label>Task<select value={task} onChange={e=>{setTask(e.target.value);setActivity('');}}><option value="">All tasks</option>{meta?.tasks.map(t=><option key={t}>{t}</option>)}</select></label><label>Activity<select value={activity} onChange={e=>setActivity(e.target.value)}><option value="">All activities</option>{meta?.activities?.map(a=><option key={a}>{a}</option>)}</select></label></div>
    {error&&<p className="production-warning" role="alert">{error}</p>}{!data&&!error&&<p role="status">Loading wages…</p>}
    {data&&<>
      {mode==='allocated'?<>
      <div className="wages-kpis"><article><span>{code?'Selected block estimate':'Mapped block estimates'}</span><strong>NGN {money(code?(data.count?data.amountMinor:null):data.mappedMinor)}</strong></article><article><span>Estate-wide allocated estimates</span><strong>NGN {money(data.mappedMinor)}</strong></article></div>
      {!code&&<p>Click a block on the map to see its allocation by month, task and activity.</p>}
      {code&&!data.selectedAreas.length&&<p className="production-warning">No allocation-area record for this block in {year}. Its estimated wages are unavailable.</p>}
      {coverage.some(c=>c.reason)&&<div className="production-warning">{coverage.filter(c=>c.reason).map(c=><p key={c.division}><b>{c.division}</b>: {c.reason}. Allocation is unavailable.</p>)}</div>}
      {code&&<div className="production-name-history">{data.selectedAreas.map(a=>{const group=coverage.find(c=>c.division===a.division);return <span key={a._id}><b>{a.sourceBlockCode} · {a.division}</b> → {a.mapBlockCode}<small>{a.mapHa==null?'Missing':a.mapHa.toLocaleString(undefined,{maximumFractionDigits:4})} map ha / {group?.mapHa.toLocaleString(undefined,{maximumFractionDigits:4})??'—'} division map ha</small><small>Rate: {group&&!group.reason?'NGN '+money(group.amountMinor/group.mapHa)+' / ha':'Unavailable'}</small><small>{group?.reason?'Allocation unavailable':group&&group.mapHa>0?`${(a.mapHa/group.mapHa*100).toFixed(3)}% allocation share`:'No division wages'} · GIS survey {a.sourcePeriod||'manual'}</small></span>;})}</div>}
      </>:<><p className="table-note">The 2025 wages workbook supplies no individual block numbers. Area estimates are available in the other view. Future block-level entries appear here.</p>{data.count?<h3>Recorded wages: NGN {money(data.amountMinor)}</h3>:<p>No recorded block wages for this selection. This is unavailable data, not zero spending.</p>}</>}
      {(mode==='recorded'||code)&&data.count>0&&<><div className="production-charts wages-charts"><Breakdown title={basis==='monthly'?'Monthly wages':'Annual wages'} rows={data.byPeriod}/><Breakdown title="Wages by task" rows={data.byTask}/><Breakdown title="Wages by activity" rows={(data.byActivity||[]).map(r=>({...r,name:task?r.activity:`${r.task} · ${r.activity}`}))}/></div><h3>{mode==='allocated'?'Allocated':'Recorded'} wages by task and activity</h3><p className="table-note">Rates are calculated separately for each period, division, task and activity. Source S/N values are row references, not permanent task codes. Annual summaries do not supply S/N. Block costs are rounded to kobo; displayed rates use four decimals.</p><div className="data-table-scroll wages-rates" tabIndex="0"><table><thead><tr>{['Period',...(!code?['Block']:[]),'Task No / S/N','Task','Activity',...(mode==='allocated'?['Rate (NGN/ha)']:[]),'Block cost (NGN)'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{data.items.map(r=><tr key={r.id}><td>{r.period}</td>{!code&&<td>{r.sourceBlockCode}</td>}<td>{r.taskNumbers?.join(', ')||r.sourceSerial||'—'}</td><td>{r.task}</td><td>{r.activity}</td>{mode==='allocated'&&<><td>{(r.rateMinorPerHa/100).toLocaleString(undefined,{minimumFractionDigits:4,maximumFractionDigits:4})}</td></>}<td>{money(r.amountMinor)}</td></tr>)}</tbody></table></div><div className="table-pagination"><button className="button" disabled={!page} onClick={()=>setPage(p=>p-1)}>Previous</button><span>{data.count.toLocaleString()} activity records · page {page+1}</span><button className="button" disabled={(page+1)*25>=data.count} onClick={()=>setPage(p=>p+1)}>Next</button></div></>}
      {mode==='allocated'&&<details><summary>Estate allocation coverage</summary><div className="data-table-scroll"><table><thead><tr><th>Division</th><th>Source wages (NGN)</th><th>Map ha</th><th>Allocation</th></tr></thead><tbody>{data.coverage.map(c=><tr key={c.division}><td>{c.division}</td><td>{money(c.amountMinor)}</td><td>{c.mapHa.toLocaleString(undefined,{maximumFractionDigits:4})}</td><td>{c.reason||'Available'}</td></tr>)}</tbody></table></div></details>}
    </>}
    </>}
  </section>;
}
